name: Firebase Hosting CI

on:
  push:
    branches:
      - main  # Run when you push to the main branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3  # Get your code

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: npm run build -- --prod  # Builds your dist/soulsync-app folder

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v1
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          channelId: live
          projectId: "soulsync-15c75"
